from webweaver.modules.project_modules.speed_fanatics.categorization.brand_handler import BrandHandler
from webweaver.modules.project_modules.speed_fanatics.categorization.category_handler import CategoryHandler
from webweaver.modules.project_modules.speed_fanatics.categorization.subcategory_handler import SubCategoryHandler
from webweaver.modules.project_modules.speed_fanatics.categorization.vehicle_handler import VehicleHandler
from webweaver.modules.project_modules.speed_fanatics.categorization.spec_handler import SpecHandler